### ISSUE TITLE
[enhancement] notify users of updated themes

### ISSUE THREAD

**Issue by n7itro** [zen-browser/theme-store#60]
There are a few ways we can do this:
- Add an 'updated' tag to the theme in the theme store
- Automatically update the theme for all users
- Notify users about theme updates in the browser / theme settings

**Comment by danm36** [comment]
I feel like all three of these would work well. Given that - for now at least - themes are strictly CSS with perhaps some boolean properties, then automatic updates could be the default without too much fear of breaking things or anything malicious being added. Within that, provide the option to opt-out of auto-updates on both a global and a per-theme basis for those that want it, and in that case provide notifications and an update button.

If themes get upgraded to also support arbitrary JavaScript, then those probably shouldn't be auto-update by default for obvious reasons. Then again, browser extensions do auto-update, so maybe it's not as big an issue, especially since Zen theme PRs get reviewed by people?

**Comment by mauro-balades** [comment]
Now themes have versions and updates for the next zen release, thanks!
